In [1]:
import numpy as np

# arange(start,stop,step) Function to make array of desired elements

In [30]:
#creating array from arange(1 to 10) without any step ie, by default 1 step

arr_1d = np.arange(1,10)
print(arr_1d)

[1 2 3 4 5 6 7 8 9]


In [31]:
#creating array from arange(2 to 21) with a step of 2 for only even numbers

arr_even = np.arange(2,21,2)
print(arr_even)

[ 2  4  6  8 10 12 14 16 18 20]


# linspace() Function to devide start point and end point into desirable parts

In [32]:
#linspace divides the points into equal propositions ie, 20 divisions between 1 to 10

arr_lins = np.linspace(1,10,20)
print(arr_lins)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


# reshape(row,column) Function for conversion of matrix shape

In [33]:
#creating 1-D array using arange() function

arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
#converting 1-D array into 2-D array using reshape() function

arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
arr_2d = arr_1d.reshape((3,4), order='c' )
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
#converting 1-D array into 3-D array using reshape() function

arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel() Function to convert N-D array into 1-D array

In [37]:
#converting 1-D array to 1-D array using ravel() function

arr_ravel = arr_1d.ravel()
print(arr_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
#converting 2-D array to 1-D array using ravel() function

arr_ravel = arr_2d.ravel()
print(arr_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
#converting 3-D array to 1-D array using ravel() function

arr_ravel = arr_3d.ravel()
print(arr_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# flatten() Fuction to convert N-D array into 1-D array

In [40]:
#converting 1-D array to 1-D array using flatten() function

arr_flatten = arr_1d.flatten()
print(arr_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
#converting 2-D array to 1-D array using flatten() function

arr_flatten = arr_2d.flatten()
print(arr_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
#converting 3-D array to 1-D array using flatten() function

arr_flatten = arr_3d.flatten()
print(arr_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# transpose() Function to transpose the matrix

In [43]:
#transposing 1-D matrix

arr_transpose = arr_1d.transpose()
print(arr_transpose)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
#transposing 2-D matrix

arr_transpose = arr_2d.transpose()
print(arr_transpose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [45]:
#transposing 3-D array

arr_transpose = arr_3d.transpose()
print(arr_transpose)

[[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]
