In [1]:
#importing numpy library
import numpy as np

In [2]:
#creating 1's array using ones() function
    #1-D array
matrix_1s = np.ones(5)
print(matrix_1s)

[1. 1. 1. 1. 1.]


In [3]:
#2-D array of 1's having default data type as float

matrix_1s = np.ones((3,4))
print(matrix_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#2-D array of 1's having data type as int

matrix_1s = np.ones((5,4), dtype=int)
print(matrix_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
#2-D array of 1's having data type as boolean

matrix_1s = np.ones((5,6), dtype=bool)
print(matrix_1s)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [6]:
#2-D array of 1's having data type as string

matrix_1s = np.ones((3,4), dtype=str)
print(matrix_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [7]:
#Creating 0's array using zeros() function
    #1-D array

matrix_0s = np.zeros(5)
print(matrix_0s)

[0. 0. 0. 0. 0.]


In [8]:
#2-D array of 0's having default data type as Float

matrix_0s = np.zeros((3,4))
print(matrix_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#2-D array of 0's having data type as int

matrix_0s = np.zeros((5,4), dtype=int)
print(matrix_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
#2-D array of 0's having data type as boolean

matrix_0s = np.zeros((4,6), dtype=bool)
print(matrix_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [11]:
#2-D array of 0's having data type as String

matrix_0s = np.zeros((3,4), dtype=str)
print(matrix_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [12]:
#Creating Empty array which has by default random values and default data type is float

matrix_empty = np.empty((3,4))
print(matrix_empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#2-D empty array having data type as int

matrix_empty = np.empty((4,5), dtype=int)
print(matrix_empty)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
