In [1]:
import numpy as np

In [2]:
#creating 2 matrix of 3*3 shape

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

print(arr1)
print()
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


# Arithematic Operations on Matrix

In [3]:
#Matrix Addition using +

arr1+arr2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [4]:
#matrix addition using built in function np.add()

np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [5]:
#matrix subtraction using -

arr1-arr2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [6]:
#matrix subtraction using built in function np.subtract()

np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [7]:
#matrix division using /

arr1 / arr2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [8]:
#matrix division using built in function np.divide()

np.divide(arr1,arr2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [9]:
#element multiplication in matrix using *

arr1*arr2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [10]:
#element multiplication in matrix using built in function np.multiply()

np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [11]:
#matrix multiplication using @

arr1 @ arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [12]:
#matrix multiplication using built in function .dot()

arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

# Built -in functions of NumPy

In [13]:
#finding maximum element from the matrix 1

np.max(arr1)

9

In [14]:
#finding maximum element from the matrix 2

np.max(arr2)

19

In [15]:
#finding maximum element's index from the matrix 1

arr1.argmax()

8

In [16]:
#finding maximum element's index from the matrix 2

arr2.argmax()

8

In [17]:
#finding maximum element of each column(axis=0) from the matrix 1

arr1.max(axis=0)

array([7, 8, 9])

In [18]:
#finding maximum element of each row(axis=1) from the matrix 1

arr1.max(axis=1)

array([3, 6, 9])

In [19]:
#finding maximum element of each column(axis=0) from the matrix 2

arr2.max(axis=0)

array([17, 18, 19])

In [20]:
#finding maximum element of each row(axis=1) from the matrix 2


arr2.max(axis=1)

array([13, 16, 19])

In [21]:
#finding minimum element from the matrix 1


arr1.min()

1

In [22]:
#finding minimum element from the matrix 2

arr2.min()

11

In [23]:
#finding minimum element's index from the matrix 1

arr1.argmin()

0

In [24]:
#finding minimum element's index from the matrix 2

arr2.argmin()

0

In [25]:
#finding minimum element of each column(axis=0) from the matrix 1

arr1.min(axis=0)

array([1, 2, 3])

In [26]:
#finding minimum element of each row(axis=1) from the matrix 1

arr1.min(axis=1)

array([1, 4, 7])

In [27]:
#finding minimum element of each column(axis=0) from the matrix 2

arr2.min(axis=0)

array([11, 12, 13])

In [28]:
#finding minimum element of each row(axis=1) from the matrix 2

arr2.min(axis=1)

array([11, 14, 17])

In [29]:
#finding sum of all the elements from matrix 1

np.sum(arr1)

45

In [30]:
#finding sum of all the elements from matrix 2

np.sum(arr2)

135

In [31]:
#finding sum of elements of each column(axis=0) from matrix 1

np.sum(arr1, axis=0)

array([12, 15, 18])

In [32]:
#finding sum of elements of each row(axis=1) from matrix 1

np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [33]:
#finding sum of elements of each column(axis=0) from matrix 2

np.sum(arr2, axis=0)

array([42, 45, 48])

In [34]:
#finding sum of elements of each row(axis=1) from matrix 2

np.sum(arr2, axis=1)

array([36, 45, 54])

In [35]:
#finding average of all the elements from matrix 1

np.mean(arr1)

5.0

In [36]:
#finding average of all the elements from matrix 2

np.mean(arr2)

15.0

In [37]:
#finding square root of all the elements from matrix 1

np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [38]:
#finding square root of all the elements from matrix 2

np.sqrt(arr2)

array([[3.31662479, 3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894]])

In [39]:
#finding standard deviation of all the elements from matrix 1

np.std(arr1)

2.581988897471611

In [40]:
#finding standard deviation of all the elements from matrix 2

np.std(arr2)

2.581988897471611

In [41]:
#finding exponent of all the elements from matrix 1

np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [42]:
#finding exponent of all the elements from matrix 2

np.exp(arr2)

array([[5.98741417e+04, 1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08]])

In [43]:
#finding normal log of all the elements from matrix 1

np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [44]:
#finding normal log of all the elements from matrix 2

np.log(arr2)

array([[2.39789527, 2.48490665, 2.56494936],
       [2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898]])

In [45]:
#finding log10 of all the elements from matrix 1

np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [46]:
#finding log10 of all the elements from matrix 2

np.log10(arr2)

array([[1.04139269, 1.07918125, 1.11394335],
       [1.14612804, 1.17609126, 1.20411998],
       [1.23044892, 1.25527251, 1.2787536 ]])