# Matrix Concatenating, stacking & splitting into pieces

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# concatenate function to add 2nd matrix behind 1st where axis=0 means row wise and axis=1 means column wise

In [4]:
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [5]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# same concatenate without any axis using Vertical & Horizontal stack function

In [6]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [7]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# Splitting the matrix into equivalent pieces

In [8]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [9]:
#splitted matrix becomes a list of arrays after splitting

list1 = np.split(arr1,2)

In [10]:
type(list1)

list

In [11]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
list1[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
type(list1[0])

numpy.ndarray

In [14]:
type(list1[1])

numpy.ndarray

In [15]:
new_arr = np.array([4,5,6,7,8,9])

In [16]:
print(new_arr)

[4 5 6 7 8 9]


# splitting the array into multiple pieces

In [17]:
np.split(new_arr,[1,3,4,5])

[array([4]), array([5, 6]), array([7]), array([8]), array([9])]