# Rndom Sampling using random library

In [1]:
import numpy as np
import random

In [2]:
arr = np.random.random(1)
print(arr)

[0.44263669]


In [3]:
np.random.random(1)

array([0.04691723])

In [4]:
np.random.random((3,4))

array([[0.71299207, 0.37912673, 0.97311676, 0.09813978],
       [0.43347492, 0.3776797 , 0.14427783, 0.28174108],
       [0.6764823 , 0.95222393, 0.01500358, 0.29607769]])

In [5]:
np.random.randint(1,5)

2

In [6]:
np.random.randint(100000,999999, (10,10))

array([[152343, 209338, 719509, 424866, 876400, 599487, 323084, 694395,
        359662, 568742],
       [199690, 945221, 556998, 470601, 673264, 573077, 489483, 706626,
        691426, 306447],
       [751712, 782442, 731196, 675738, 176397, 786940, 355549, 547218,
        157646, 185409],
       [193579, 904658, 237135, 987961, 255430, 912011, 286864, 425921,
        228372, 585795],
       [155833, 733798, 896328, 269728, 433949, 103844, 777772, 166943,
        983591, 217102],
       [257601, 259209, 961502, 875721, 141935, 998535, 371238, 717408,
        543076, 526165],
       [652599, 657983, 923971, 880623, 520183, 459604, 885410, 930212,
        569401, 187682],
       [555062, 899876, 818193, 608474, 984132, 744563, 380087, 828447,
        827778, 494577],
       [322512, 743822, 868554, 332457, 367824, 528088, 666603, 330118,
        778635, 954653],
       [840806, 497495, 285552, 702516, 436015, 803226, 672386, 391598,
        846496, 548127]])

In [7]:
np.random.randint(1000,9999, (2,4,6))

array([[[9849, 4261, 1742, 7748, 6271, 4426],
        [5486, 7713, 9654, 3547, 5713, 1667],
        [6030, 5977, 6202, 1842, 6800, 5045],
        [5248, 6667, 4072, 9010, 9251, 3177]],

       [[7991, 8075, 8749, 6098, 3508, 8669],
        [6129, 2101, 1131, 6951, 8183, 4064],
        [2980, 5611, 7027, 8438, 3799, 3542],
        [2171, 7482, 3116, 9000, 7634, 7638]]])

In [8]:
np.random.seed(10)
np.random.randint(100000,999999, (10,10))

array([[445353, 860957, 981167, 543712, 717841, 205595, 633660, 399741,
        904336, 208445],
       [378385, 240296, 895721, 810912, 852106, 980680, 345156, 203952,
        940036, 280463],
       [675883, 922616, 619531, 631578, 525505, 424808, 845316, 649838,
        703825, 312659],
       [570070, 574565, 374445, 500115, 444473, 805918, 313645, 792060,
        363510, 161214],
       [885054, 763641, 856364, 861153, 491711, 655833, 953796, 673723,
        128178, 304893],
       [997101, 421942, 303671, 397566, 799128, 645163, 965948, 508650,
        719736, 435241],
       [646831, 316594, 799856, 313622, 939000, 392235, 167217, 191566,
        297767, 385387],
       [649660, 294004, 938394, 574976, 247500, 790821, 970404, 487143,
        992248, 138744],
       [830930, 371724, 435030, 733122, 575496, 410031, 607341, 151855,
        938653, 831270],
       [953238, 905461, 360842, 291126, 224427, 532752, 448940, 825472,
        419550, 429206]])

In [9]:
np.random.seed(21)
np.random.randint(100000,999999, (5,5))

array([[705129, 957295, 302552, 764324, 181968],
       [163856, 666392, 885827, 581980, 801026],
       [426385, 210794, 494862, 125023, 138316],
       [674269, 508829, 616329, 116118, 856016],
       [889742, 209412, 727686, 274676, 443355]])

In [10]:
np.random.seed(10)
np.random.randint(100000,999999, (10,10))

array([[445353, 860957, 981167, 543712, 717841, 205595, 633660, 399741,
        904336, 208445],
       [378385, 240296, 895721, 810912, 852106, 980680, 345156, 203952,
        940036, 280463],
       [675883, 922616, 619531, 631578, 525505, 424808, 845316, 649838,
        703825, 312659],
       [570070, 574565, 374445, 500115, 444473, 805918, 313645, 792060,
        363510, 161214],
       [885054, 763641, 856364, 861153, 491711, 655833, 953796, 673723,
        128178, 304893],
       [997101, 421942, 303671, 397566, 799128, 645163, 965948, 508650,
        719736, 435241],
       [646831, 316594, 799856, 313622, 939000, 392235, 167217, 191566,
        297767, 385387],
       [649660, 294004, 938394, 574976, 247500, 790821, 970404, 487143,
        992248, 138744],
       [830930, 371724, 435030, 733122, 575496, 410031, 607341, 151855,
        938653, 831270],
       [953238, 905461, 360842, 291126, 224427, 532752, 448940, 825472,
        419550, 429206]])

In [11]:
np.random.seed(21)
np.random.randint(100000,999999, (5,5))

array([[705129, 957295, 302552, 764324, 181968],
       [163856, 666392, 885827, 581980, 801026],
       [426385, 210794, 494862, 125023, 138316],
       [674269, 508829, 616329, 116118, 856016],
       [889742, 209412, 727686, 274676, 443355]])

In [12]:
np.random.rand(3)

array([0.42572943, 0.96701234, 0.28204171])

In [13]:
np.random.rand(4,3)

array([[0.58215916, 0.49947697, 0.29106427],
       [0.5698933 , 0.87576259, 0.9264645 ],
       [0.95695305, 0.2927576 , 0.23259317],
       [0.26696986, 0.08517213, 0.75085542]])

In [14]:
np.random.randn(4)

array([ 1.46843073, -1.57759274, -0.33332448, -1.14080155])

In [15]:
np.random.randn(5,6)

array([[ 0.18600019,  1.3838356 , -0.56470433,  1.43021653,  0.43183952,
         0.37345132],
       [ 2.36003641,  0.47940186, -0.75098688,  0.68816325,  0.25394905,
         0.37327912],
       [ 1.20615504, -0.2784506 , -0.83695257,  1.46791738,  1.52534912,
         0.63780229],
       [ 0.69187471, -1.56752533, -1.12203431,  0.00845602, -1.07848279,
         1.85915999],
       [ 0.25098143, -0.11167111,  1.12606814,  0.92215289, -0.7352208 ,
        -0.18933449]])

In [16]:
list = [1,2,3,4,5,6,7,8,9,10]

np.random.choice(list)

10

In [17]:
np.random.permutation(list)

array([ 3,  1,  9,  5,  6,  7,  8, 10,  4,  2])